### ISSUE TITLE
Run command not working on all platforms (Cross-Platform-Compability)

### ISSUE THREAD

**Issue by Impelon** [TheBiochemic/go-ai-doodle#1]
After installing Go on Windows (Windows 8), running the program with the suggested 
`go run *.go`
from the commandline (cmd) inside the folder will not work. 
Building the project as a executable for the specific platform and running that will work, though.
For Windows this will work: `go build -buildmode=exe`.

For further reading see: 
- https://stackoverflow.com/questions/23695448/golang-run-all-go-files-within-current-directory-through-the-command-line-mul
- https://golang.org/cmd/go/#hdr-Description_of_build_modes

I'd suggest to edit the README.md describing these limitations to allow for an easy setup for users new to Golang.

**Comment by TheBiochemic** [comment]
see https://github.com/TheBiochemic/go-ai-doodle/commit/668558dea3ba708f186faec938d84ecc340a8422
